[package]
name = "fractal_window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.8"
image = "0.24.6"
rayon = "1.7.0"
rustyline = "12.0.0"
softbuffer = "0.3.0"
winit = "0.28.6"
